# Generated by Django 5.0.1 on 2024-02-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movableTableRowApp', '0003_product_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='position',
            field=models.IntegerField(unique=True),
        ),
    ]
