# Generated by Django 5.0.1 on 2024-02-06 08:34

import django.db.models.constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movableTableRowApp', '0004_alter_product_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='position',
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('position',), name='position_init_deferred_uniq'),
        ),
    ]
